base_url = "https://ad-oliviero.github.io"
title = "Adriano Oliviero"
description = "My Portfolio"
default_language = "en"

[extra]
author = "Adriano Oliviero"
role = "Computer Engineering Student"
github = "https://github.com/ad-oliviero"
email = "adrianoliviero23@gmail.com"
resume = "https://rxresu.me/ad-oliviero/cv"
